name    'ispavailability-graphite'
version '0.0.2'
source 'https://github.com/electrical/puppet-graphite'
author 'ispavailability'
license 'Apache License, Version 2.0'
summary 'Module for managing and configuring graphite'
description 'Module for managing and configuring graphite'
project_page 'https://github.com/electrical/puppet-graphite'
dependency 'puppetlabs/stdlib', '>= 3.0.0'
dependency 'ispavailability/file_concat', '>= 0.0.1'
